### ISSUE TITLE
[feature request] TypeScript support

### ISSUE THREAD

**Issue by DAmNRelentless** [ptkdev/ptkdev-logger#7]
### Feature description
It would be nice if this awesome looking logger would also be available for TypeScript usage.
This would require some typings. Also you are getting an error like this when trying to use it
with TypeScript:
```
Cannot invoke an object which is possibly 'undefined'.
```
I am always using strict mode for my TS projects to avoid issues.

### Feature motivation
Well TypeScript gets more and more popular and is a lot better than JavaScript in a ton of aspects.
Especially console applications which could use this awesome logger are often written in TS which
would make this a perfect package for it.

**Comment by ptkdev** [comment]
Hi @DAmNRelentless !
The ptkdev-logger support the typescript language on version >= **v1.7.0**

You can provide snippet of code you use?

**Comment by ptkdev** [comment]
My test:
![logger-typescript](https://user-images.githubusercontent.com/442844/90639215-ac946200-e22e-11ea-9d08-babf2ab30189.png)

**Comment by ptkdev** [comment]
@DAmNRelentless try **v1.7.1**, now work with strict mode.

**Comment by DAmNRelentless** [comment]
Thanks for the fast response. :)
I tested v1.7.1. This is my TypeScript code:
```
import Logger from '@ptkdev/logger';
const logger = new Logger();
```
Following error:
```
const logger = new Logger();
               ^
TypeError: logger_1.default is not a constructor
    at Object.<anonymous> (/mnt/c/Users/Relentless/Documents/GitKraken/zeus/src/zeus.ts:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Module.m._compile (/mnt/c/Users/Relentless/Documents/GitKraken/zeus/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/mnt/c/Users/Relentless/Documents/GitKraken/zeus/node_modules/ts-node/src/index.ts:861:12)    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at main (/mnt/c/Users/Relentless/Documents/GitKraken/zeus/node_modules/ts-node/src/bin.ts:227:14)
    at Object.<anonymous> (/mnt/c/Users/Relentless/Documents/GitKraken/zeus/node_modules/ts-node/src/bin.ts:513:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeus@1.0.0 start: `ts-node src/zeus.ts`
npm ERR! Exit status 1
```

Node version: v14.8.0
NPM version: 6.14.7
VSCode version: 1.48.0
TypeScript version: 3.9.7

**Comment by ptkdev** [comment]
Thanks for this debug log. I try reproduce this bug 🐛 stay tuned :)

**Comment by ptkdev** [comment]
Solution:
`npm install @types/node --save`

Your code:
```javascript
const Logger = require("@ptkdev/logger");
const logger = new Logger();
```

**Comment by ptkdev** [comment]
Now i work how compile with `import` and why import don't work.

**Comment by DAmNRelentless** [comment]
Yes, works like a charm now. Glad that issue report was able to help you out. Great logger, keep it up! :)
